[package]
name = "rust_repo_generator"
version = "0.1.0"
edition = "2021"
authors = ["Dmitry Melnikov <d.dash.mv@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-husky = "1.5.0"
